### ISSUE TITLE
pulseaudio blocks audio devices for other processes using ALSA

### ISSUE THREAD

**Issue by eglia** [home-assistant/audio#13] opened 2020-03-11 09:17 UTC
I'm running hassio (Supervisor 209, homeassistant 0.106.6) on a generic linux host (Ubuntu 19.10). The same host runs Kodi which uses ALSA to play sound via the TV (HDMI). Pulseaudio is not installed on the host.

The hassio docker container starts a pulseaudio daemon which prevents Kodi from accessing the audio device via ALSA. As a workaround, I currently have to stop the supervisor and audio containers, start Kodi and then restart the supervisor & audio container. This allows Kodi to grab the audio devices.

I don't need homeassistant to output any audio, so I need some way to prevent the audio container from blocking the audio devices (or preventing the container from starting at all).

**Comment by frenck** [comment] 2020-03-11 09:43
Duplicate of #12

**Closed by frenck** 2020-03-11 09:43 UTC
